# Generated by Django 3.1.4 on 2020-12-14 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_auto_20201213_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtuber',
            old_name='is_featured',
            new_name='is_featured',
        ),
    ]
